project:
  type: website
  resources:
    - robots.txt

website:
  title: "Soyoka Okamura"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    css: styles.css
    fontsize: 1.0em
    smooth-scroll: true
    metadata:
      robots: "noindex, nofollow"
